asset_list:
  - 'AAPL'
  - 'GOOG'
  - 'MSFT'
  - 'AMZN'
  - 'TSLA'
date_range:
  start: '2020-01-01'
  end: '2024-01-01'
fees:
  trading_fee: 0.001
  slippage: 0.0005
learning:
  learning_rate: 0.0003
  gamma: 0.99
  batch_size: 64
  epochs: 10
seeds:
  random_seed: 42
  torch_seed: 42
paths:
  data_dir: './data/'
  model_dir: './models/'
  log_dir: './logs/' 